# Generated by Django 4.2 on 2025-05-09 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('alert_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('destination_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('packet_info', models.TextField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkMonitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('monitor_start', 'Monitor Started'), ('monitor_stop', 'Monitor Stopped'), ('error', 'Error'), ('info', 'Information')], max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NetworkTrafficStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('packets_captured', models.IntegerField(default=0)),
                ('bytes_captured', models.BigIntegerField(default=0)),
                ('packets_per_second', models.FloatField(default=0.0)),
                ('bytes_per_second', models.FloatField(default=0.0)),
                ('protocol_distribution', models.TextField(default='{}')),
                ('active_connections', models.IntegerField(default=0)),
                ('unique_ips', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VulnerabilityCheckup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('scan_type', models.CharField(default='standard', max_length=50)),
                ('total_vulnerabilities', models.IntegerField(default=0)),
                ('high_vulnerabilities', models.IntegerField(default=0)),
                ('medium_vulnerabilities', models.IntegerField(default=0)),
                ('low_vulnerabilities', models.IntegerField(default=0)),
                ('scan_duration', models.DurationField(blank=True, null=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerability_checkups', to='scanner.target')),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('cve_id', models.CharField(blank=True, max_length=20, null=True)),
                ('affected_component', models.CharField(max_length=255)),
                ('remediation_steps', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], default='open', max_length=20)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('checkup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='scanner.vulnerabilitycheckup')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='scanner.target')),
            ],
        ),
    ]
