# Generated by Django 4.2 on 2025-05-09 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_networkalert_networkmonitorlog_networktrafficstats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(default='standard', max_length=50)),
                ('port_range', models.CharField(default='1-1024', max_length=255)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('open_ports_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_scans', to='scanner.target')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='PortInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_number', models.IntegerField()),
                ('is_open', models.BooleanField(default=True)),
                ('service_name', models.CharField(default='unknown', max_length=100)),
                ('service_version', models.CharField(blank=True, max_length=100, null=True)),
                ('banner', models.TextField(blank=True, null=True)),
                ('protocol', models.CharField(default='tcp', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('scan_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_info', to='scanner.portscanresult')),
            ],
            options={
                'ordering': ['port_number'],
            },
        ),
    ]
